<template>
    <div class="loadingio-spinner-spinner-c3dm1msoxsw">
        <div class="ldio-zqq9lbbi71">
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
        </div>
    </div>
</template>



<style>
@keyframes ldio-zqq9lbbi71 {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-zqq9lbbi71 div {
  left: 0px;
  top: 0px;
  position: absolute;
  animation: ldio-zqq9lbbi71 linear 1s infinite;
  /* background: #fe718d; */
  background: white;

  width: 10px;
    height: 5px;
  border-radius: 3.72px / 3px;
  transform-origin: 5px 15px;
}.ldio-zqq9lbbi71 div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: white;
}.ldio-zqq9lbbi71 div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: white;
}
.loadingio-spinner-spinner-c3dm1msoxsw {
    width: 30px;
    height: 30px;
  display: inline-block;
  background: none;
}
.ldio-zqq9lbbi71 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-zqq9lbbi71 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>